SELECT DISTINCT ?cd ?l ?i ?iLabel ?ct ?ctLabel ?rgb ?o ?oLabel WITH{SELECT ?i ?cd ?lat1 ?lon1 (sample(?op)as?op)WHERE{{VALUES ?i {wd:Q601091}}UNION{wd:Q601091 wdt:P521 ?i} ?i wdt:P625 ?cd;p:P625/psv:P625 ?y.?y wikibase:geoLatitude ?lat1;wikibase:geoLongitude ?lon1.}GROUP BY ?i ?cd ?lat1 ?lon1}AS%s
WITH{SELECT ?l ?o ?t WHERE{INCLUDE %s.wd:Q601091 p:P521 ?nss; p:P625/psv:P625 ?y2.?y2 wikibase:geoLatitude ?lati1;wikibase:geoLongitude ?long1 .?nss ps:P521 ?ns.?ns p:P625/psv:P625 ?z.?z wikibase:geoLatitude ?lat2;wikibase:geoLongitude ?lon2.OPTIONAL{?nss pq:P137 ?o}FILTER(STR(?i)< STR(?ns)).BIND(CONCAT('LINESTRING(',STR(?long1),' ',STR(?lati1),',',STR(?lon2),' ',STR(?lat2),')')AS?str).BIND(STRDT(?str,geo:wktLiteral)AS?l)}}AS%l
WHERE{{INCLUDE%s}UNION{INCLUDE%l}.BIND(IF(BOUND(?l),IF(BOUND(?o),"00f","f00"),"007f00") as ?rgb)SERVICE wikibase:label{bd:serviceParam wikibase:language "en".}}#
